

services:
  waymo-e2e-loader:
    build: .
    volumes:
      - ./waymo_dataset/downloads:/waymo_dataset/downloads
      - ./waymo_dataset/results:/waymo_dataset/results
    environment:
      - RESULTS_DIR=/waymo_dataset/results
    working_dir: /app